# Generated by Django 3.1.1 on 2021-06-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hblog', '0016_auto_20210615_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
